// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: packages/util/sound-mixing-proto/index.proto
#ifndef GRPC_packages_2futil_2fsound_2dmixing_2dproto_2findex_2eproto__INCLUDED
#define GRPC_packages_2futil_2fsound_2dmixing_2dproto_2findex_2eproto__INCLUDED

#include "index.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class Mixer final {
 public:
  static constexpr char const* service_full_name() {
    return "Mixer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::ChunkedData>> mixing(::grpc::ClientContext* context, const ::RequestVoiceMixing& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::ChunkedData>>(mixingRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ChunkedData>> Asyncmixing(::grpc::ClientContext* context, const ::RequestVoiceMixing& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ChunkedData>>(AsyncmixingRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ChunkedData>> PrepareAsyncmixing(::grpc::ClientContext* context, const ::RequestVoiceMixing& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::ChunkedData>>(PrepareAsyncmixingRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void mixing(::grpc::ClientContext* context, ::RequestVoiceMixing* request, ::grpc::ClientReadReactor< ::ChunkedData>* reactor) = 0;
      #else
      virtual void mixing(::grpc::ClientContext* context, ::RequestVoiceMixing* request, ::grpc::experimental::ClientReadReactor< ::ChunkedData>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderInterface< ::ChunkedData>* mixingRaw(::grpc::ClientContext* context, const ::RequestVoiceMixing& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::ChunkedData>* AsyncmixingRaw(::grpc::ClientContext* context, const ::RequestVoiceMixing& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::ChunkedData>* PrepareAsyncmixingRaw(::grpc::ClientContext* context, const ::RequestVoiceMixing& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::ChunkedData>> mixing(::grpc::ClientContext* context, const ::RequestVoiceMixing& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::ChunkedData>>(mixingRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::ChunkedData>> Asyncmixing(::grpc::ClientContext* context, const ::RequestVoiceMixing& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::ChunkedData>>(AsyncmixingRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::ChunkedData>> PrepareAsyncmixing(::grpc::ClientContext* context, const ::RequestVoiceMixing& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::ChunkedData>>(PrepareAsyncmixingRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void mixing(::grpc::ClientContext* context, ::RequestVoiceMixing* request, ::grpc::ClientReadReactor< ::ChunkedData>* reactor) override;
      #else
      void mixing(::grpc::ClientContext* context, ::RequestVoiceMixing* request, ::grpc::experimental::ClientReadReactor< ::ChunkedData>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReader< ::ChunkedData>* mixingRaw(::grpc::ClientContext* context, const ::RequestVoiceMixing& request) override;
    ::grpc::ClientAsyncReader< ::ChunkedData>* AsyncmixingRaw(::grpc::ClientContext* context, const ::RequestVoiceMixing& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::ChunkedData>* PrepareAsyncmixingRaw(::grpc::ClientContext* context, const ::RequestVoiceMixing& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_mixing_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status mixing(::grpc::ServerContext* context, const ::RequestVoiceMixing* request, ::grpc::ServerWriter< ::ChunkedData>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_mixing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_mixing() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_mixing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mixing(::grpc::ServerContext* /*context*/, const ::RequestVoiceMixing* /*request*/, ::grpc::ServerWriter< ::ChunkedData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestmixing(::grpc::ServerContext* context, ::RequestVoiceMixing* request, ::grpc::ServerAsyncWriter< ::ChunkedData>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_mixing<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_mixing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_mixing() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::RequestVoiceMixing, ::ChunkedData>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::RequestVoiceMixing* request) { return this->mixing(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_mixing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mixing(::grpc::ServerContext* /*context*/, const ::RequestVoiceMixing* /*request*/, ::grpc::ServerWriter< ::ChunkedData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::ChunkedData>* mixing(
      ::grpc::CallbackServerContext* /*context*/, const ::RequestVoiceMixing* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::ChunkedData>* mixing(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::RequestVoiceMixing* /*request*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_mixing<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_mixing<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_mixing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_mixing() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_mixing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mixing(::grpc::ServerContext* /*context*/, const ::RequestVoiceMixing* /*request*/, ::grpc::ServerWriter< ::ChunkedData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_mixing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_mixing() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_mixing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mixing(::grpc::ServerContext* /*context*/, const ::RequestVoiceMixing* /*request*/, ::grpc::ServerWriter< ::ChunkedData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestmixing(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_mixing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_mixing() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->mixing(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_mixing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mixing(::grpc::ServerContext* /*context*/, const ::RequestVoiceMixing* /*request*/, ::grpc::ServerWriter< ::ChunkedData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* mixing(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* mixing(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_mixing : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_mixing() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler< ::RequestVoiceMixing, ::ChunkedData>(std::bind(&WithSplitStreamingMethod_mixing<BaseClass>::Streamedmixing, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_mixing() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status mixing(::grpc::ServerContext* /*context*/, const ::RequestVoiceMixing* /*request*/, ::grpc::ServerWriter< ::ChunkedData>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status Streamedmixing(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::RequestVoiceMixing,::ChunkedData>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_mixing<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_mixing<Service > StreamedService;
};


#endif  // GRPC_packages_2futil_2fsound_2dmixing_2dproto_2findex_2eproto__INCLUDED
