FROM node:14

#作業ディレクトリを移動
WORKDIR /usr/app
  
COPY package.json .
COPY lerna.json .
COPY tsconfig.json .
COPY yarn.lock .
COPY packages/ ./packages/



#lernaをインストール
RUN yarn global add lerna
RUN lerna bootstrap
RUN lerna run build
CMD [ "yarn", "--cwd", "./packages/presentation/klasa", "start" ]