FROM node:14-alpine AS build-bin

WORKDIR /usr/app

RUN apk add --no-cache --virtual .ojt build-base

COPY packages/util/open-jtalk/soft ./packages/util/open-jtalk/soft

RUN cd packages/util/open-jtalk/soft/hts_engine_API-1.10 \
    && find ./ -type f -print | xargs chmod 777 \
    && ./configure  \
    && make \
    && make install 

RUN cd packages/util/open-jtalk/soft/open_jtalk-1.11 \
    && find ./ -type f -print | xargs chmod 777 \
    && ./configure --with-charset=UTF-8 \
    && make \
    && make install 

RUN apk del .ojt

FROM node:14-alpine AS runtime

WORKDIR /usr/app

RUN apk add ffmpeg
RUN yarn global add pm2

ENV OPEN_JTALK_BIN /usr/local/bin/open_jtalk
ENV OPEN_JTALK_DIC /usr/local/dic
ENV HTS_VOICE_NORMAL /usr/app/packages/util/open-jtalk/htsvoice/hts_voice_nitech_jp_atr503_m001-1.05/nitech_jp_atr503_m001.htsvoice
ENV HTS_VOICE_ANGRY /usr/app/packages/util/open-jtalk/htsvoice/htsvoice-tohoku-f01-master/tohoku-f01-angry.htsvoice
ENV HTS_VOICE_HAPPY /usr/app/packages/util/open-jtalk/htsvoice/htsvoice-tohoku-f01-master/tohoku-f01-happy.htsvoice
ENV HTS_VOICE_NEUTRAL /usr/app/packages/util/open-jtalk/htsvoice/htsvoice-tohoku-f01-master/tohoku-f01-neutral.htsvoice
ENV HTS_VOICE_SAD /usr/app/packages/util/open-jtalk/htsvoice/htsvoice-tohoku-f01-master/tohoku-f01-sad.htsvoice
ENV HTS_VOICE_MEI_ANGRY /usr/app/packages/util/open-jtalk/htsvoice/MMDAgent_Example-1.8/Voice/mei/mei_angry.htsvoice
ENV HTS_VOICE_MEI_BASHFUL /usr/app/packages/util/open-jtalk/htsvoice/MMDAgent_Example-1.8/Voice/mei/mei_bashful.htsvoice
ENV HTS_VOICE_MEI_HAPPY /usr/app/packages/util/open-jtalk/htsvoice/MMDAgent_Example-1.8/Voice/mei/mei_happy.htsvoice
ENV HTS_VOICE_MEI_NORMAL /usr/app/packages/util/open-jtalk/htsvoice/MMDAgent_Example-1.8/Voice/mei/mei_normal.htsvoice
ENV HTS_VOICE_MEI_SAD /usr/app/packages/util/open-jtalk/htsvoice/MMDAgent_Example-1.8/Voice/mei/mei_sad.htsvoice
ENV HTS_VOICE_TAKUMI_ANGRY /usr/app/packages/util/open-jtalk/htsvoice/MMDAgent_Example-1.8/Voice/takumi/takumi_angry.htsvoice
ENV HTS_VOICE_TAKUMI_HAPPY /usr/app/packages/util/open-jtalk/htsvoice/MMDAgent_Example-1.8/Voice/takumi/takumi_happy.htsvoice
ENV HTS_VOICE_TAKUMI_NORMAL /usr/app/packages/util/open-jtalk/htsvoice/MMDAgent_Example-1.8/Voice/takumi/takumi_normal.htsvoice
ENV HTS_VOICE_TAKUMI_SAD /usr/app/packages/util/open-jtalk/htsvoice/MMDAgent_Example-1.8/Voice/takumi/takumi_sad.htsvoice

ENV KUROMOJI_DIC_PATH /usr/app/node_modules/kuromoji/dict

COPY --from=build-bin /usr/local/bin/open_jtalk /usr/local/bin/open_jtalk
COPY --from=build-bin /usr/local/dic /usr/local/dic

COPY packages/util/open-jtalk/htsvoice ./packages/util/open-jtalk/htsvoice
COPY kick.js ./
COPY lerna.json ./
COPY tsconfig.json ./
COPY package.json ./
COPY yarn.lock ./

COPY packages/pdomain ./packages/pdomain
COPY packages/util/fixed-dsl ./packages/util/fixed-dsl
COPY packages/util/periodical-dsl ./packages/util/periodical-dsl
COPY packages/util/timing-to-notify-dsl ./packages/util/timing-to-notify-dsl
COPY packages/usecase ./packages/usecase
COPY packages/repository/gss ./packages/repository/gss
COPY packages/repository/schedule ./packages/repository/schedule
COPY packages/presentation/klasa ./packages/presentation/klasa

RUN apk add --no-cache --virtual .ojt git \
    && yarn global add lerna \
    && lerna bootstrap \
    && lerna run build \
    && yarn global remove lerna \
    && yarn cache clean \
    && apk del .ojt

CMD [ "pm2","--no-daemon","start","kick.js","--name","pwrd-event"]