import * as moment from "moment-timezone";
import { GameEvent } from "pdomain/game-event";
import { VoiceKindArray } from "./text2speech/engine";

export type PWRD_LANG_TYPE = {
  COMMAND_CONF_GUILD_MEMBER_DESCRIPTION: string;
  GOOGLE_SPREAD_SHEET_UPDATE_SUCCESS: string;
  INVALID_GOOGLE_SPREAD_SHEET_FORMAT: string;
  NOTIFY_TO_NOTIFICATION_CHANNEL: (
    event: GameEvent,
    notificationTime: moment.Moment,
    now: moment.Moment
  ) => string;
  COMMAND_LIST_DESCRIPTION: string;
  COMMAND_NEXT_DESCRIPTION: string;
  COMMAND_PUT_DESCRIPTION: string;
  COMMAND_UPDATE_DESCRIPTION: string;
  COMMAND_START_DESCRIPTION: string;
  COMMAND_START_SUCCESS: string;
  COMMAND_START_FAILED_WITH_USER_NOT_IN_VC: string;
  COMMAND_START_FAILED_WITH_BOT_NOT_JOINABLE: string;
  COMMAND_END_SUCCESS: string;
  COMMAND_END_DESCRIPTION: string;
  COMMAND_ADD_WORD_DESCRIPTION: string;
  COMMAND_ADD_WORD_SUCCESS: string;
  COMMAND_DELETE_WORD_DESCRIPTION: string;
  COMMAND_DELETE_WORD_SUCCESS: string;
  COMMAND_START_EXTENDED_HELP: (kinds: typeof VoiceKindArray) => string;
  COMMAND_KUROMOJI_DESCRIPTION: string;
  COMMAND_JUMANPP_DESCRIPTION: string;
};
export const COMMAND_CONF_GUILD_MEMBER_DESCRIPTION =
  "COMMAND_CONF_GUILD_MEMBER_DESCRIPTION";
export const INVALID_GOOGLE_SPREAD_SHEET_FORMAT =
  "INVALID_GOOGLE_SPREAD_SHEET_FORMAT";
export const NOTIFY_TO_NOTIFICATION_CHANNEL = "NOTIFY_TO_NOTIFICATION_CHANNEL";

export const COMMAND_LIST_DESCRIPTION = "COMMAND_LIST_DESCRIPTION";

export const COMMAND_NEXT_DESCRIPTION = "COMMAND_NEXT_DESCRIPTION";

export const COMMAND_PUT_DESCRIPTION = "COMMAND_PUT_DESCRIPTION";

export const COMMAND_UPDATE_DESCRIPTION = "COMMAND_UPDATE_DESCRIPTION";
export const COMMAND_UPDATE_SUCCESS = "GOOGLE_SPREAD_SHEET_UPDATE_SUCCESS";

export const COMMAND_START_DESCRIPTION = "COMMAND_START_DESCRIPTION";
export const COMMAND_START_EXTENDED_HELP = "COMMAND_START_EXTENDED_HELP";
export const COMMAND_START_SUCCESS = "COMMAND_START_SUCCESS";
export const COMMAND_START_FAILED_WITH_USER_NOT_IN_VC =
  "COMMAND_START_FAILED_WITH_USER_NOT_IN_VC";
export const COMMAND_START_FAILED_WITH_BOT_NOT_JOINABLE =
  "COMMAND_START_FAILED_WITH_BOT_NOT_JOINABLE";

export const COMMAND_END_DESCRIPTION = "COMMAND_END_DESCRIPTION";
export const COMMAND_END_SUCCESS = "COMMAND_END_SUCCESS";

export const COMMAND_ADD_WORD_DESCRIPTION = "COMMAND_ADD_WORD_DESCRIPTION";
export const COMMAND_ADD_WORD_SUCCESS = "COMMAND_ADD_WORD_SUCCESS";

export const COMMAND_DELETE_WORD_DESCRIPTION =
  "COMMAND_DELETE_WORD_DESCRIPTION";
export const COMMAND_DELETE_WORD_SUCCESS = "COMMAND_DELETE_WORD_SUCCESS";

export const COMMAND_KUROMOJI_DESCRIPTION = "COMMAND_KUROMOJI_DESCRIPTION";
export const COMMAND_JUMANPP_DESCRIPTION = "COMMAND_JUMANPP_DESCRIPTION";
