import * as moment from "moment-timezone";


import { GameEvent } from "pdomain/game-event";
export type PWRD_LANG_TYPE={
    GOOGLE_SPREAD_SHEET_UPDATE_SUCCESS:string,
    INVALID_GOOGLE_SPREAD_SHEET_FORMAT:string,
    NOTIFY_TO_NOTIFICATION_CHANNEL: (event:GameEvent,notificationTime:moment.Moment,now:moment.Moment)=>string,
    COMMAND_LIST_DESCRIPTION:string,
    COMMAND_NEXT_DESCRIPTION:string,
    COMMAND_PUT_DESCRIPTION:string,
    COMMAND_UPDATE_DESCRIPTION:string
}

export const COMMAND_UPDATE_SUCCESS="GOOGLE_SPREAD_SHEET_UPDATE_SUCCESS";

export const INVALID_GOOGLE_SPREAD_SHEET_FORMAT="INVALID_GOOGLE_SPREAD_SHEET_FORMAT";
export const NOTIFY_TO_NOTIFICATION_CHANNEL="NOTIFY_TO_NOTIFICATION_CHANNEL";
export const COMMAND_LIST_DESCRIPTION="COMMAND_LIST_DESCRIPTION";
export const COMMAND_NEXT_DESCRIPTION="COMMAND_NEXT_DESCRIPTION";
export const COMMAND_PUT_DESCRIPTION="COMMAND_PUT_DESCRIPTION";
export const COMMAND_UPDATE_DESCRIPTION="COMMAND_UPDATE_DESCRIPTION";