import { VoiceKindArray } from "./text2speech/engine";

export type GUJ_CORE_LANG_TYPE = {
  COMMAND_START_DESCRIPTION: string;
  COMMAND_START_SUCCESS: string;
  COMMAND_START_FAILED_WITH_USER_NOT_IN_VC: string;
  COMMAND_START_FAILED_WITH_BOT_NOT_JOINABLE: string;
  COMMAND_END_SUCCESS: string;
  COMMAND_END_DESCRIPTION: string;
  COMMAND_SKIP_DESCRIPTION: string;
  COMMAND_START_EXTENDED_HELP: (kinds: typeof VoiceKindArray) => string;
  META_COMMAND_DELETED: string;
};

export const COMMAND_START_DESCRIPTION = "COMMAND_START_DESCRIPTION";
export const COMMAND_START_EXTENDED_HELP = "COMMAND_START_EXTENDED_HELP";
export const COMMAND_START_SUCCESS = "COMMAND_START_SUCCESS";
export const COMMAND_START_FAILED_WITH_USER_NOT_IN_VC =
  "COMMAND_START_FAILED_WITH_USER_NOT_IN_VC";
export const COMMAND_START_FAILED_WITH_BOT_NOT_JOINABLE =
  "COMMAND_START_FAILED_WITH_BOT_NOT_JOINABLE";

export const COMMAND_END_DESCRIPTION = "COMMAND_END_DESCRIPTION";
export const COMMAND_END_SUCCESS = "COMMAND_END_SUCCESS";

export const COMMAND_SKIP_DESCRIPTION = "COMMAND_END_DESCRIPTION";
