apiVersion: v1
kind: ConfigMap
metadata:
  name: guj-bots-common-config
data:
  GUILD_UTILS_J_PROVIDER : mongodb
  GUJ_MIXER_RPC_SERVER : guj-mixer:50051
  GUJ_MIXER_KEYS : /keys
  NODE_ENV : production
  GUJ_USE_GOOGLE_STACKDRIVER : "true"
  GOOGLE_APPLICATION_CREDENTIALS: /guj-bots-sa-cred/gcp-credentials.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guj-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guj-main
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: guj-main
    spec:
      containers:
      - name: guj-main
        image: tignear/guj-main:local-dev
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: guj-bots-common-config
        env:
        - name: GUILD_UTILS_J_MAIN_DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: main
        - name: MONGO_DB
          value: main
        - name: MONGO_CONNECTION
          valueFrom:
            secretKeyRef:
              name: mongo-connection
              key: main
        - name: GUJ_DEFAULT_PREFIX
          value: $
        - name: GUJ_LAUNCH_CHANNEL
          valueFrom:
            secretKeyRef: 
              name: discord-token
              key: launch-channel
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: keys
          mountPath: /keys
        - name: guj-bots-sa-cred
          mountPath: /guj-bots-sa-cred
      volumes:
      - name: keys
        configMap:
          name: client-keys
      - name: guj-bots-sa-cred
        secret:
          secretName: guj-bots-sa-cred
---
apiVersion: v1
kind: Service
metadata:
  name: guj-main
spec:
  ports:
    - name: guj-main
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: guj-main
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guj-sub-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guj-sub-1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: guj-sub-1
    spec:
      containers:
      - name: guj-sub
        image: tignear/guj-sub:local-dev
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: guj-bots-common-config
        env:
        - name: GUILD_UTILS_J_SUB_DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: sub-1
        - name: GUILD_UTILS_J_PROVIDER
          value: mongodb
        - name: MONGO_CONNECTION
          valueFrom:
            secretKeyRef:
              name: mongo-connection
              key: sub-1
        - name: MONGO_DB
          value: sub1
        - name: GUILD_UTILS_J_RPC_SERVER
          value: guj-main:50051
        - name: GUJ_LAUNCH_CHANNEL
          valueFrom:
            secretKeyRef: 
              name: discord-token
              key: launch-channel
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: keys
          mountPath: /keys
        - name: guj-bots-sa-cred
          mountPath: /guj-bots-sa-cred
      volumes:
      - name: keys
        configMap:
          name: client-keys
      - name: guj-bots-sa-cred
        secret:
          secretName: guj-bots-sa-cred      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guj-sub-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guj-sub-2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: guj-sub-2
    spec:
      containers:
      - name: guj-sub
        image: tignear/guj-sub:local-dev
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: guj-bots-common-config
        env:
        - name: GUILD_UTILS_J_SUB_DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: sub-2
        - name: GUILD_UTILS_J_PROVIDER
          value: mongodb
        - name: MONGO_CONNECTION
          valueFrom:
            secretKeyRef:
              name: mongo-connection
              key: sub-2
        - name: MONGO_DB
          value: sub2
        - name: GUILD_UTILS_J_RPC_SERVER
          value: guj-main:50051
        - name: GUJ_DEFAULT_PREFIX
          value: $,
        - name: GUJ_THEME_COLOR
          value: "0xFF420E"
        - name: GUJ_LAUNCH_CHANNEL
          valueFrom:
            secretKeyRef: 
              name: discord-token
              key: launch-channel
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: keys
          mountPath: /keys
        - name: guj-bots-sa-cred
          mountPath: /guj-bots-sa-cred
      volumes:
      - name: keys
        configMap:
          name: client-keys
      - name: guj-bots-sa-cred
        secret:
          secretName: guj-bots-sa-cred
