import { GameEvent } from "domain_game-event";

export const COMMAND_CONF_GUILD_MEMBER_DESCRIPTION =
  "COMMAND_CONF_GUILD_MEMBER_DESCRIPTION";
export const INVALID_GOOGLE_SPREAD_SHEET_FORMAT =
  "INVALID_GOOGLE_SPREAD_SHEET_FORMAT";
export const NOTIFY_TO_NOTIFICATION_CHANNEL = "NOTIFY_TO_NOTIFICATION_CHANNEL";

export const COMMAND_LIST_DESCRIPTION = "COMMAND_LIST_DESCRIPTION";

export const COMMAND_NEXT_DESCRIPTION = "COMMAND_NEXT_DESCRIPTION";

export const COMMAND_PUT_DESCRIPTION = "COMMAND_PUT_DESCRIPTION";

export const COMMAND_UPDATE_DESCRIPTION = "COMMAND_UPDATE_DESCRIPTION";
export const COMMAND_UPDATE_SUCCESS = "GOOGLE_SPREAD_SHEET_UPDATE_SUCCESS";

export const COMMAND_ADD_WORD_DESCRIPTION = "COMMAND_ADD_WORD_DESCRIPTION";
export const COMMAND_ADD_WORD_SUCCESS = "COMMAND_ADD_WORD_SUCCESS";

export const COMMAND_DELETE_WORD_DESCRIPTION =
  "COMMAND_DELETE_WORD_DESCRIPTION";
export const COMMAND_DELETE_WORD_SUCCESS = "COMMAND_DELETE_WORD_SUCCESS";

export const COMMAND_KUROMOJI_DESCRIPTION = "COMMAND_KUROMOJI_DESCRIPTION";
export const COMMAND_JUMANPP_DESCRIPTION = "COMMAND_JUMANPP_DESCRIPTION";

export type GUJ_MAIN_LANG_TYPE = {
  GOOGLE_SPREAD_SHEET_UPDATE_SUCCESS: string;
  INVALID_GOOGLE_SPREAD_SHEET_FORMAT: string;
  NOTIFY_TO_NOTIFICATION_CHANNEL: (
    event: GameEvent,
    notificationTime: moment.Moment,
    now: moment.Moment
  ) => string;
  COMMAND_CONF_GUILD_MEMBER_DESCRIPTION: string;
  COMMAND_LIST_DESCRIPTION: string;
  COMMAND_NEXT_DESCRIPTION: string;
  COMMAND_PUT_DESCRIPTION: string;
  COMMAND_UPDATE_DESCRIPTION: string;
  COMMAND_KUROMOJI_DESCRIPTION: string;
  COMMAND_JUMANPP_DESCRIPTION: string;
  COMMAND_ADD_WORD_DESCRIPTION: string;
  COMMAND_ADD_WORD_SUCCESS: string;
  COMMAND_DELETE_WORD_DESCRIPTION: string;
  COMMAND_DELETE_WORD_SUCCESS: string;
};
