import { GameEvent } from "domain_game-event";

export const COMMAND_CONF_GUILD_MEMBER_DESCRIPTION =
  "COMMAND_CONF_GUILD_MEMBER_DESCRIPTION";
export const INVALID_GOOGLE_SPREAD_SHEET_FORMAT =
  "INVALID_GOOGLE_SPREAD_SHEET_FORMAT";
export const NOTIFY_TO_NOTIFICATION_CHANNEL = "NOTIFY_TO_NOTIFICATION_CHANNEL";

export const COMMAND_LIST_DESCRIPTION = "COMMAND_LIST_DESCRIPTION";

export const COMMAND_NEXT_DESCRIPTION = "COMMAND_NEXT_DESCRIPTION";

export const COMMAND_PUT_DESCRIPTION = "COMMAND_PUT_DESCRIPTION";

export const COMMAND_UPDATE_DESCRIPTION = "COMMAND_UPDATE_DESCRIPTION";
export const COMMAND_UPDATE_SUCCESS = "GOOGLE_SPREAD_SHEET_UPDATE_SUCCESS";

export const COMMAND_ADD_WORD_DESCRIPTION = "COMMAND_ADD_WORD_DESCRIPTION";
export const COMMAND_ADD_WORD_SUCCESS_WITH_CREATE =
  "COMMAND_ADD_WORD_SUCCESS_WITH_CREATE";
export const COMMAND_ADD_WORD_SUCCESS_WITH_OVERWRITE =
  "COMMAND_ADD_WORD_SUCCESS_WITH_OVERWRITE";

export const COMMAND_DELETE_WORD_DESCRIPTION =
  "COMMAND_DELETE_WORD_DESCRIPTION";
export const COMMAND_DELETE_WORD_SUCCESS_WITH_DELETE =
  "COMMAND_DELETE_WORD_SUCCESS_WITH_DELETE";
export const COMMAND_DELETE_WORD_SUCCESS_WITH_NONE =
  "COMMAND_DELETE_WORD_SUCCESS_WITH_NONE";

export const COMMAND_IMPORT_COMPLETE = "COMMAND_IMPORT_COMPLETE";

export const COMMAND_EXPORT_SUCCESS = "COMMAND_EXPORT_SUCCESS";
export const COMMAND_CLEAR_SUCCESS = "COMMAND_CLEAR_SUCCESS";
export const COMMAND_KUROMOJI_DESCRIPTION = "COMMAND_KUROMOJI_DESCRIPTION";
export const COMMAND_JUMANPP_DESCRIPTION = "COMMAND_JUMANPP_DESCRIPTION";
export const INVALID_ADD_FORMAT = "INVALID_ADD_FORMAT";
export const INVALID_REMOVE_FORMAT = "INVALID_REMOVE_FORMAT";
export const INVALID_UPDATE_FORMAT = "INVALID_UPDATE_FORMAT";
export const INVALID_INDEX_RANGE = "INVALID_INDEX_RANGE";
export const COMMAND_MAIN_DICT_INVALID_REMOVE_FORMAT =
  "COMMAND_MAIN_DICT_INVALID_REMOVE_FORMAT";
export const INVALID_SIMPLE_DICT_ENTRY = "INVALID_SIMPLE_DICT_ENTRY";
export const INVALID_MAIN_DICT_ENTRY = "INVALID_MAIN_DICT_ENTRY";
export const COMMAND_MAIN_DICT_REQUIRE_KEY = "COMMAND_MAIN_DICT_REQUIRE_KEY";
export type GUJ_MAIN_LANG_TYPE = {
  GOOGLE_SPREAD_SHEET_UPDATE_SUCCESS: string;
  INVALID_GOOGLE_SPREAD_SHEET_FORMAT: string;
  NOTIFY_TO_NOTIFICATION_CHANNEL: (
    event: GameEvent,
    notificationTime: moment.Moment,
    now: moment.Moment
  ) => string;
  COMMAND_CONF_GUILD_MEMBER_DESCRIPTION: string;
  COMMAND_LIST_DESCRIPTION: string;
  COMMAND_NEXT_DESCRIPTION: string;
  COMMAND_PUT_DESCRIPTION: string;
  COMMAND_UPDATE_DESCRIPTION: string;
  COMMAND_KUROMOJI_DESCRIPTION: string;
  COMMAND_JUMANPP_DESCRIPTION: string;
  COMMAND_ADD_WORD_DESCRIPTION: string;
  COMMAND_CLEAR_SUCCESS: string;
  COMMAND_ADD_WORD_SUCCESS_WITH_CREATE: (from: string, to: string) => string;
  COMMAND_ADD_WORD_SUCCESS_WITH_OVERWRITE: (
    from: { from: string; to: string },
    to: { from: string; to: string }
  ) => string;
  COMMAND_DELETE_WORD_DESCRIPTION: string;
  COMMAND_IMPORT_COMPLETE: string;
  COMMAND_EXPORT_SUCCESS: string;
  COMMAND_DELETE_WORD_SUCCESS_WITH_DELETE: (from: string, to: string) => string;
  COMMAND_DELETE_WORD_SUCCESS_WITH_NONE: (from: string) => string;
  INVALID_ADD_FORMAT: string;
  INVALID_REMOVE_FORMAT: string;
  INVALID_UPDATE_FORMAT: string;
  INVALID_INDEX_RANGE: string;
  INVALID_SIMPLE_DICT_ENTRY: string;
  INVALID_MAIN_DICT_ENTRY: string;
  COMMAND_MAIN_DICT_INVALID_REMOVE_FORMAT: string;
  COMMAND_MAIN_DICT_REQUIRE_KEY: string;
};
