name: sub-bots
on: 
  push: 
    branches: production-subs
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          lfs: true
      - uses: rlespinasse/github-slug-action@v2.x
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          username: tignear
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Sub.Dockerfile
          tags: |
            guildutils/sub:latest
            guildutils/sub:${{ env.GITHUB_SHA_SHORT }}
          build-args: GIT_SHORT_COMMIT_HASH=${{ env.GITHUB_SHA_SHORT }}
          cache-from: guildutils/sub:latest
  deploy-sub-1:
    needs: build
    runs-on: ubuntu-latest
    env:
      GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH_DEPLOY }}
    steps:
      - uses: rlespinasse/github-slug-action@v2.x
      - uses: azure/setup-kubectl@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: guild-utils
      - run: gcloud container clusters get-credentials guj --region=asia-northeast1-b --project=guild-utils
      - run: kubectl set image --record deployment/guj-sub-1 guj-sub=guildutils/sub:${{ env.GITHUB_SHA_SHORT }}
      - run: kubectl set image --record deployment/guj-sub-2 guj-sub=guildutils/sub:${{ env.GITHUB_SHA_SHORT }}
  deploy-sub-2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@v2.x
      - uses: azure/setup-kubectl@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: guild-utils
      - run: gcloud container clusters get-credentials guj --region=asia-northeast1-b --project=guild-utils
      - run: kubectl rollout status deployment/guj-sub-1
      - run: kubectl rollout status deployment/guj-sub-2